spring.application.name=readcycle

spring.datasource.url=jdbc:mysql://localhost:3306/readcycle
spring.datasource.username=root
spring.datasource.password=bxik2942

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
